dependencies:
- name: elasticsearch
  version: ^1.27.3
  repository: https://hub.helm.sh/charts
  condition: elasticsearch.enabled
- name: mongodb-replicaset
  version: ^3.9.5
  repository: https://hub.helm.sh/charts
  condition: mongodb-replicaset.enabled
